# fly.toml app configuration file generated for telegrampickmebot on 2023-10-27T10:02:33+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "telegrampickmebot"
primary_region = "sin"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[processes]
  app = ""

[[services]]
  protocol = "tcp"
  internal_port = 80
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
